#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export EDITOR=code
export VISUAL=$EDITOR
export LSCOLORS="exfxcxdxbxegedabagacad"

export ANDROID_HOME=$HOME/BuildTools/android/sdk-2022-01-19
export ANDROID_SDK_ROOT=$ANDROID_HOME
export ANDROID_AVD_HOME=$HOME/.android/avd

export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

export REACT_EDITOR=code

export GEM_HOME=$HOME/.gem
export PATH="$PATH:$GEM_HOME/bin"

export YARN_HOME=$HOME/.yarn
export PATH="$PATH:$YARN_HOME/bin"

export PRIVATE_GITHUB_TOKEN="revoked"

export NVM_DIR="$HOME/.nvm"
export GPG_TTY=$(tty)
